### ISSUE TITLE
When writing the response, calling panic is a bad idea

### ISSUE THREAD

**Issue by hydrogen18** [corneldamian/json-binding#2]
From `response.go`

```
        if len(data) > 0 {
            _, err = rw.Write(data)
            if err != nil {
                rw.Write([]byte("{\"Error\": \"writing error\"")) //try to send error ???
                panic("I was unable to write data to the client: " + err.Error())
            }
```

If there is data to write to the client, this code calls the `Write` method to write it. 

However, if an error is encountered, it then tries to write a hand-rolled JSON error message to the client. Since `rw.Write` just returned an error this is likely to return exactly the same error. For example, perhaps the client terminated the TCP connection used to make the HTTP request as the response was being written. In other words, it does nothing useful. If the client did somehow get that message, it would be very confusing because they would have a partial response of some kind followed by the JSON error message. This would likely be unparseable to many clients. I suggest removing the second call `rw.Write` entirely.

Next, `panic` is called. This behavior should be controllable by the caller of `binding.Response`. It is probably OK to `panic` by default here. Many http frameworks for go include the notion of some default error handler. You should probably just call the `errorHandler` function that is already user defined. It might be a little confusing at first to some users, but it is a better alternative than just calling `panic`.

**Comment by corneldamian** [comment]
You are right about the second write. But i think panic it's better then calling the errorHandler, because at least on the default one it will try a second status code write and another write to the socket.

**Comment by corneldamian** [comment]
I've changed the way it's handled
- call errorHandler
- in default error handler will panic if there it was something written to the client (statusCode != 0)
