### ISSUE TITLE
Examples in README allows invalid parameter in json POST request, it there a way to validate or you need to manual validation ?

### ISSUE THREAD

**Issue by Jitendrakry** [corneldamian/json-binding#3]
{"Success":"User ss Pass: "}montana@localhost ~ $ curl -X POST -d '{"Useraaaaaaaaaaaaname":"ss"}' http://192.168.241.183:8080/auth/login
{"Success":"User  Pass: "}user@localhost ~ $ curl -X POST -d '{"Usaaaaaeraaaaaaaaaaaaname":"ss"}' http://192.168.241.183:8080/auth/login
{"Success":"User  Pass: "}user@localhost ~ $ curl -X POST -d '{"Usaaaaaeraaaaaaaaatttttttttttttttttttttttttttaaaname":"ss"}' http://192.168.241.183:8080/auth/login
{"Success":"User  Pass: "}user@localhost ~ $

**Comment by corneldamian** [comment]
This library is only mapping from json to struct, you can use something like http://godoc.org/gopkg.in/validator.v2 for validation.
