### ISSUE TITLE
Erro 400

### ISSUE THREAD

**Issue by brunoksato** [corneldamian/json-binding#4]
How use 2 methods ? 

   router := web.New(Context{})

```
//static
router.Middleware(web.StaticMiddleware("public"))

//
router.Middleware(binding.Response(nil))
router.Middleware(binding.Request(Authenticate{}, nil)).Post("/auth/login", Authentication)

router.Middleware(binding.Request(User{}, nil)).Post("/api/users", UserCreate)
```

**Comment by corneldamian** [comment]
Sorry for the late response, the error can appear because you don't have the json in the body of the request or it's invalid.

If you look in the body of the POST request you should see something like:

```
{"Username":"x", "Password":"y"}
```
